apps/watch/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),
    path('shop/', views.ShopListView.as_view(), name='shop'),
    path('contact/', views.contact, name='contact'),
    path('watch/<slug:slug>/', views.product_detail, name='watch'),
    path('search/', views.SearchResultsView.as_view(), name='search_results'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.watch.urls')),
    path('blog/', include('apps.pages.urls')),
    path('cart/', include('apps.orders.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/pages/models.py
from django.db import models
from django.urls import reverse_lazy


class NewsCategory(models.Model):
    name = models.CharField('name', max_length=255, blank=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'news category'
        verbose_name_plural = 'news category'


class News(models.Model):
    title = models.CharField('title', max_length=255, blank=False)
    content = models.TextField('content', max_length=1000, blank=False)
    category = models.ForeignKey(NewsCategory, related_name='category_news', on_delete=models.CASCADE)
    image = models.ImageField('image', upload_to='news/', default='no_image.jpg', help_text='Image resolution 750x375')
    created_at = models.DateTimeField('date', auto_now_add=True)
    publish = models.BooleanField('publish', default=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'news'
        verbose_name_plural = 'news'

    def get_absolute_url(self):
        return reverse_lazy('blog_detail', kwargs={'pk': self.pk})


class About(models.Model):
    title = models.CharField('page name', max_length=255, blank=False)
    slug = models.SlugField('slug', max_length=255, blank=False, unique=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'about'
        verbose_name_plural = 'about'


class AboutItem(models.Model):
    page = models.ForeignKey(About, related_name='about_about_items', on_delete=models.CASCADE)
    title = models.CharField('title', max_length=255, blank=False)
    content = models.TextField('content', max_length=1000, blank=False)

    def __str__(self):
        return self.page.title


class Contact(models.Model):
    title = models.CharField('page name', max_length=255, blank=False)
    slug = models.SlugField('slug', max_length=255, blank=False, unique=True)
    address = models.CharField('address', max_length=255, blank=False)
    contact_phone = models.CharField('contact phone', max_length=16, blank=False)
    email = models.EmailField("email", max_length=100, blank=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'contact'
        verbose_name_plural = 'contact'

apps/watch/models.py
from django.db import models
from django.urls import reverse_lazy


class Category(models.Model):
    title = models.CharField('category', max_length=255, blank=False)
    slug = models.SlugField('slug', max_length=255, blank=False, unique=True)
    publish = models.BooleanField('publish', default=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_watch(self):
        return self.category_products.all()


class CaseMaterial(models.Model):
    title = models.CharField('case material', max_length=255, blank=False)
    slug = models.SlugField('slug', max_length=255, blank=False, unique=True)
    publish = models.BooleanField('publish', default=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'case material'
        verbose_name_plural = 'case materials'


class Country(models.Model):
    title = models.CharField('country', max_length=255, blank=False)
    slug = models.SlugField('slug', max_length=255, blank=False, unique=True)
    publish = models.BooleanField('publish', default=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'country'
        verbose_name_plural = 'countries'


class Brand(models.Model):
    title = models.CharField('brand', max_length=255, blank=False)
    slug = models.SlugField('slug', max_length=255, blank=False, unique=True)
    publish = models.BooleanField('publish', default=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'brand'
        verbose_name_plural = 'brands'


class Product(models.Model):
    title = models.CharField('watch', max_length=255, blank=False)
    slug = models.SlugField('slug', max_length=255, blank=False, unique=True)
    category = models.ForeignKey(Category, related_name='category_products', on_delete=models.CASCADE)
    case_material = models.ForeignKey(CaseMaterial, related_name='case_material_products', on_delete=models.CASCADE)
    country = models.ForeignKey(Country, related_name='country_products', on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, related_name='brand_products', on_delete=models.CASCADE)
    image = models.ImageField("image", upload_to='images/', default='no_image.jpg',
                              help_text='Image resolution 380x361')
    with_discount = models.BooleanField('with discount', default=False)
    publish = models.BooleanField('publish', default=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-id']
        verbose_name = 'watch'
        verbose_name_plural = 'watch'

    def get_absolute_url(self):
        return reverse_lazy('watch', kwargs={'slug': self.slug})

    def get_regular_price(self):
        if self.product_prices.filter(price_type__title='regular').exists():
            return self.product_prices.get(price_type__title='regular').price

    def get_discounted_price(self):
        if self.product_prices.filter(price_type__title='discounted').exists():
            return self.product_prices.get(price_type__title='discounted').price

    def get_current_price(self):
        if not self.with_discount:
            return self.get_regular_price()
        else:
            return self.get_discounted_price()


class PriceType(models.Model):
    title = models.CharField('price type', max_length=255, help_text='"regular" or "discounted"', blank=False)
    publish = models.BooleanField('publish', default=True)

    def __str__(self):
        return self.title


class Price(models.Model):
    product = models.ForeignKey(Product, related_name='product_prices', on_delete=models.CASCADE)
    price_type = models.ForeignKey(PriceType, related_name='price_type_prices', on_delete=models.CASCADE)
    price = models.PositiveIntegerField('price', blank=False)
    publish = models.BooleanField('publish', default=True)

    def __str__(self):
        return self.product.title

    class Meta:
        unique_together = 'product', 'price_type'

watch/models.py
from django.db import models


class Category(models.Model):
    title = models.CharField('category', max_length=255, blank=False)
    slug = models.SlugField('slug', max_length=255, blank=False)
    publish = models.BooleanField('publish', default=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'


class CaseMaterial(models.Model):
    title = models.CharField('case material', max_length=255, blank=False)
    slug = models.SlugField('slug', max_length=255, blank=False)
    publish = models.BooleanField('publish', default=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'case material'
        verbose_name_plural = 'case materials'


class Country(models.Model):
    title = models.CharField('country', max_length=255, blank=False)
    slug = models.SlugField('slug', max_length=255, blank=False)
    publish = models.BooleanField('publish', default=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'country'
        verbose_name_plural = 'countries'


class Brand(models.Model):
    title = models.CharField('brand', max_length=255, blank=False)
    slug = models.SlugField('slug', max_length=255, blank=False)
    publish = models.BooleanField('publish', default=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'brand'
        verbose_name_plural = 'brands'


class Product(models.Model):
    title = models.CharField('watch', max_length=255, blank=False)
    category = models.ForeignKey(Category, related_name='category_products', on_delete=models.CASCADE)
    case_material = models.ForeignKey(CaseMaterial, related_name='case_material_products', on_delete=models.CASCADE)
    country = models.ForeignKey(Country, related_name='country_products', on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, related_name='brand_products', on_delete=models.CASCADE)
    slug = models.SlugField('slug', max_length=255, blank=False)
    publish = models.BooleanField('publish', default=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'watch'
        verbose_name_plural = 'watch'


class PriceType(models.Model):
    title = models.CharField('brand', max_length=255, blank=False)
    publish = models.BooleanField('publish', default=True)

    def __str__(self):
        return self.title


class Price(models.Model):
    product = models.ForeignKey(Product, related_name='product_prices', on_delete=models.CASCADE)
    price_type = models.ForeignKey(PriceType, related_name='price_type_prices', on_delete=models.CASCADE)
    price = models.PositiveIntegerField('price', blank=False)
    publish = models.BooleanField('publish', default=True)

    def __str__(self):
        return self.product.title

apps/watch/forms.py
from django import forms
from apps.orders.models import OrderDetail


class ProductForm(forms.ModelForm):
    class Meta:
        model = OrderDetail
        fields = ['count', ]
        widgets = {
            'count': forms.NumberInput(attrs={'class': 'product_count_item input-number'}),
        }

apps/watch/views.py
from django.shortcuts import render
from django.http import Http404
from django.db.models import Q
from django.contrib.sessions.models import Session

from django.views.generic import ListView
from apps.watch.models import Product
from apps.pages.models import About, Contact
from apps.watch.forms import ProductForm
from apps.orders.models import Order, OrderDetail


def index(request):
    context = {}

    discount = Product.objects.filter(publish=True, with_discount=True)
    context['discount'] = discount
    new_arrival = Product.objects.filter(publish=True, ).order_by('-pk')[:3]
    context['new_arrival'] = new_arrival
    return render(request, 'watch/index.html', context)


def about(request):
    context = {}
    if About.objects.filter(slug='about').exists():
        page = About.objects.get(slug='about')
    else:
        raise Http404('Страница "О НАС" не найдена')

    context['page'] = page
    return render(request, 'watch/about.html', context)


def contact(request):
    context = {}
    if Contact.objects.filter(slug='contact').exists():
        page = Contact.objects.get(slug='contact')
    else:
        raise Http404('Страница "КОНТАКТЫ" не найдена')

    context['page'] = page
    return render(request, 'watch/contact.html', context)


class ShopListView(ListView):
    paginate_by = 6
    model = Product
    queryset = Product.objects.filter(publish=True)
    template_name = 'watch/shop.html'


# class BlogListView(ListView):
#     paginate_by = 3
#     model = News
#     template_name = 'watch/blog.html'
#
#
# class BlogDetailView(DetailView):
#     model = News
#     template_name = 'watch/blog_detail.html'


def product_detail(request, slug):
    context = {}

    if Product.objects.filter(slug=slug).exists():
        product = Product.objects.get(slug=slug)
        context['product'] = product
    else:
        raise Http404('Страница не найдена')

    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            order = get_current_order(request)
            count = form.cleaned_data['count']

            if order.details.filter(product=product).exists():
                # calc exists order_details
                order_details = order.details.filter(product=product).first()
                order_details.count += count
                order_details.save()
            else:
                # create new order_details
                order_details = OrderDetail()
                order_details.order = order
                order_details.count = count
                order_details.product = product
                order_details.price = product.get_current_price()
                order_details.save()
        context['success'] = True
        context['form'] = ProductForm()

    else:

        context['form'] = ProductForm()
    return render(request, 'watch/product_detail.html', context)


def get_current_order(request):
    if Order.objects.filter(session__session_key=request.session.session_key, status__isnull=True):
        return Order.objects.filter(session__session_key=request.session.session_key, status__isnull=True).first()
    else:
        order = Order()
        if not request.session.session_key:
            request.session.save()
        session = Session.objects.get(session_key=request.session.session_key)
        order.session = session
        order.save()
        return order


class SearchResultsView(ListView):
    model = Product
    template_name = 'watch/search_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        object_list = Product.objects.filter(
            Q(title__contains=query) |
            Q(category__title__contains=query) |
            Q(case_material__title__contains=query) |
            Q(country__title__contains=query) |
            Q(brand__title__contains=query)
        )
        return object_list

templates/watch/blog.html
{% extends 'watch/base.html' %}

{% block title %}
Блог
{% endblock %}

{% block content %}
<div class="slider-area ">
    <div class="single-slider slider-height2 d-flex align-items-center">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="hero-cap text-center">
                        <h2>БЛОГ</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--================Blog Area =================-->
<section class="blog_area section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mb-5 mb-lg-0">
                <nav style="--bs-breadcrumb-divider: '';" aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Блог</li>
                    </ol>
                </nav>
            </div>
            <div class="col-lg-8 mb-5 mb-lg-0">
                <div class="blog_left_sidebar">
                    {% for news in news_list %}
                    <article class="blog_item">
                        <div class="blog_item_img">
                            <img class="card-img rounded-0" src="{{ news.image.url }}" alt="">
                            <a href="#" class="blog_item_date">
                                <h3>{{ news.created_at|date:"d" }}</h3>
                                <p>{{ news.created_at|date:"M" }}</p>
                            </a>
                        </div>
                        <div class="blog_details">
                            <a class="d-inline-block" href="single-blog.html">
                                <h2>{{ news.title }}</h2>
                            </a>
                            <p>{{ news.content|truncatechars:150|safe}}</p>
                            <ul class="blog-info-link">
                                <li><a href="#"><i class="far fa-check-square"></i>{{ news.category }}</a></li>
                            </ul>
                        </div>
                    </article>
                    {% endfor %}


                    <nav class="blog-pagination justify-content-center d-flex">
                        <ul class="pagination">

                            {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a href="?page={{ page_obj.previous_page_number }}"
                                   class="page-link" aria-label="Previous">
                                    <i class="ti-angle-left"></i>
                                </a>
                            </li>
                            {% endif %}

                            <li class="page-item active">
                                <a href="#" class="page-link" onclick="return false">{{ page_obj.number }}</a>
                            </li>

                            {% if page_obj.has_next %}
                            <li class="page-item">
                                <a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Next">
                                    <i class="ti-angle-right"></i>
                                </a>
                            </li>
                            {% endif %}

                        </ul>
                    </nav>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="blog_right_sidebar">
                    <aside class="single_sidebar_widget search_widget">
                        <form action="#">
                            <div class="form-group">
                                <div class="input-group mb-3">
                                    <input type="text" class="form-control" placeholder='Search Keyword'
                                        onfocus="this.placeholder = ''"
                                        onblur="this.placeholder = 'Введите слово'">
                                    <div class="input-group-append">
                                        <button class="btns" type="button"><i class="ti-search"></i></button>
                                    </div>
                                </div>
                            </div>
                            <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                                type="submit">Поиск</button>
                        </form>
                    </aside>
                    <aside class="single_sidebar_widget post_category_widget">
                        <h4 class="widget_title">Категории</h4>
                        <ul class="list cat-list">
                            <li>
                                <a href="#" class="d-flex">
                                    <p>Resaurant food</p>
                                    <p>(37)</p>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="d-flex">
                                    <p>Travel news</p>
                                    <p>(10)</p>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="d-flex">
                                    <p>Modern technology</p>
                                    <p>(03)</p>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="d-flex">
                                    <p>Product</p>
                                    <p>(11)</p>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="d-flex">
                                    <p>Inspiration</p>
                                    <p>21</p>
                                </a>
                            </li>
                            <li>
                                <a href="#" class="d-flex">
                                    <p>Health Care (21)</p>
                                    <p>09</p>
                                </a>
                            </li>
                        </ul>
                    </aside>
                    <aside class="single_sidebar_widget newsletter_widget">
                        <h4 class="widget_title">Подпишитесь на НАС</h4>

                        <form action="#">
                            <div class="form-group">
                                <input type="email" class="form-control" onfocus="this.placeholder = ''"
                                    onblur="this.placeholder = 'Enter email'" placeholder='Enter email' required>
                            </div>
                            <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                                type="submit">Подписаться</button>
                        </form>
                    </aside>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/watch/search_results.html
{% extends 'watch/base.html' %}

{% block title %}
Поиск
{% endblock %}

{% block content %}
<div class="slider-area ">
    <div class="single-slider slider-height2 d-flex align-items-center">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="hero-cap text-center">
                        <h2>Результаты поиска</h2>
                        {% if not product_list %}
                        <br>
                        <h2 style="color: #db0303; font-size: 400%; text-transform:uppercase;">Совпадений не найдено</h2>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% if product_list %}
<section class="popular-items latest-padding">
    <div class="container">
        <nav style="--bs-breadcrumb-divider: '';" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li id="breadcrumb" class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
                <li class="breadcrumb-item active" aria-current="page">Результаты поиска</li>
            </ol>
        </nav>
        <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                <div class="row">
                    {% for watch in product_list %}
                        <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6">
                            <div class="single-popular-items mb-50 text-center">
                                <div class="popular-img">
                                    <img src="{{ watch.image.url }}" alt="">
                                </div>
                                <div class="popular-caption">
                                    <h3><a href="{{ watch.get_absolute_url }}">{{ watch.title }}</a></h3>
                                    {% if watch.with_discount %}
                                        <span><del>${{ watch.get_regular_price }}</del> ${{ watch.get_discounted_price }}</span>
                                    {% else %}
                                        <span>${{ watch.get_regular_price }}</span>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    {% endif %}
    </div>
</section>
{% endblock %}

templates/watch/shop.html
{% extends 'watch/base.html' %}
{% load my_tags %}

{% block title %}
Покупки
{% endblock %}

{% block content %}
<!-- Hero Area Start-->
<div class="slider-area ">
    <div class="single-slider slider-height2 d-flex align-items-center">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="hero-cap text-center">
                        <h2>Watch Shop</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Hero Area End-->
<!-- Latest Products Start -->
<section class="popular-items latest-padding">
    <div class="container">
        <nav style="--bs-breadcrumb-divider: '';" aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
                <li class="breadcrumb-item active" aria-current="page">Покупки</li>
            </ol>
        </nav>
        <div class="row product-btn justify-content-between mb-40">
            <div class="properties__button">
                <!--Nav Button  -->
                <nav>
                    <div class="nav nav-tabs" id="nav-tab" role="tablist">
                            <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Все</a>
                        {% get_category as categories %}
                        {% for category in categories %}
                            <a class="nav-item nav-link" id="nav-{{ category.slug }}-tab" data-toggle="tab" href="#nav-{{ category.slug }}" role="tab" aria-controls="nav-{{ category.slug }}" aria-selected="false">{{ category.title }}</a>
                        {% endfor %}
                    </div>
                </nav>
                <!--End Nav Button  -->
            </div>
            <!-- Grid and List view -->
            <div class="grid-list-view">
            </div>
        </div>
        <!-- Nav Card -->
        <div class="tab-content" id="nav-tabContent">
         <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                        <div class="row">
                            {% for watch in product_list %}
                                <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6">
                                    <div class="single-new-pro mb-30 text-center">
                                        <div class="product-img">
                                            <a href="{{ watch.get_absolute_url }}#breadcrumb"><img
                                                    src="{{ watch.image.url }}" alt=""></a>
                                        </div>
                                        <div class="product-caption">
                                            <h3><a href="{{ watch.get_absolute_url }}#breadcrumb">{{ watch.title }}</a>
                                            </h3>
                                            {% if watch.with_discount %}
                                                <span><del>{{ watch.get_regular_price }} руб.</del> {{ watch.get_discounted_price }} руб.</span>
                                            {% else %}
                                                <span>{{ watch.get_regular_price }} руб.</span>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
            <!-- card one -->
            {% for category in categories %}
                <div class="tab-pane fade" id="nav-{{ category.slug }}" role="tabpanel"
                     aria-labelledby="nav-{{ category.slug }}-tab">
                    <div class="row">
                        {% for watch in category.get_watch %}
                            <div class="col-xl-4 col-lg-4 col-md-6 col-sm-6">
                                <div class="single-new-pro mb-30 text-center">
                                    <div class="product-img">
                                        <a href="{{ watch.get_absolute_url }}#breadcrumb"><img
                                                src="{{ watch.image.url }}" alt=""></a>
                                    </div>
                                    <div class="product-caption">
                                        <h3><a href="{{ watch.get_absolute_url }}#breadcrumb">{{ watch.title }}</a></h3>
                                        {% if watch.with_discount %}
                                            <span><del>{{ watch.get_regular_price }} руб.</del> {{ watch.get_discounted_price }} руб.</span>
                                        {% else %}
                                            <span>{{ watch.get_regular_price }} руб.</span>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            {% endfor %}
        </div>
        <!-- End Nav Card -->
    </div>
    <nav class="blog-pagination justify-content-center d-flex">
        <ul class="pagination">

            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a href="?page={{ page_obj.previous_page_number }}"
                       class="page-link" aria-label="Previous">
                        <i class="ti-angle-left"></i>
                    </a>
                </li>
            {% endif %}

            <li class="page-item active">
                <a href="#" class="page-link" onclick="return false">{{ page_obj.number }}</a>
            </li>

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Next">
                        <i class="ti-angle-right"></i>
                    </a>
                </li>
            {% endif %}

        </ul>
    </nav>
</section>
{% endblock %}